apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mluq169ng-python 
  janus-idp.io/tekton: mluq169ng-python
  backstage.io/kubernetes-id: mluq169ng-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mluq169ng-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  