apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mluq169ng-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mluq169ng-python 
  name: mluq169ng-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mluq169ng-python 
